//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumCertificate) DeepCopyInto(out *QuantumCertificate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumCertificate.
func (in *QuantumCertificate) DeepCopy() *QuantumCertificate {
	if in == nil {
		return nil
	}
	out := new(QuantumCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumCertificate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumCertificateList) DeepCopyInto(out *QuantumCertificateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QuantumCertificate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumCertificateList.
func (in *QuantumCertificateList) DeepCopy() *QuantumCertificateList {
	if in == nil {
		return nil
	}
	out := new(QuantumCertificateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumCertificateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumCertificateSpec) DeepCopyInto(out *QuantumCertificateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumCertificateSpec.
func (in *QuantumCertificateSpec) DeepCopy() *QuantumCertificateSpec {
	if in == nil {
		return nil
	}
	out := new(QuantumCertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumCertificateStatus) DeepCopyInto(out *QuantumCertificateStatus) {
	*out = *in
	if in.CertificateReference != nil {
		in, out := &in.CertificateReference, &out.CertificateReference
		*out = new(ObjectReference)
		**out = **in
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumCertificateStatus.
func (in *QuantumCertificateStatus) DeepCopy() *QuantumCertificateStatus {
	if in == nil {
		return nil
	}
	out := new(QuantumCertificateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumDecapsulateSecret) DeepCopyInto(out *QuantumDecapsulateSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumDecapsulateSecret.
func (in *QuantumDecapsulateSecret) DeepCopy() *QuantumDecapsulateSecret {
	if in == nil {
		return nil
	}
	out := new(QuantumDecapsulateSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumDecapsulateSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumDecapsulateSecretList) DeepCopyInto(out *QuantumDecapsulateSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QuantumDecapsulateSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumDecapsulateSecretList.
func (in *QuantumDecapsulateSecretList) DeepCopy() *QuantumDecapsulateSecretList {
	if in == nil {
		return nil
	}
	out := new(QuantumDecapsulateSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumDecapsulateSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumDecapsulateSecretSpec) DeepCopyInto(out *QuantumDecapsulateSecretSpec) {
	*out = *in
	out.PrivateKeyRef = in.PrivateKeyRef
	if in.CiphertextRef != nil {
		in, out := &in.CiphertextRef, &out.CiphertextRef
		*out = new(ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumDecapsulateSecretSpec.
func (in *QuantumDecapsulateSecretSpec) DeepCopy() *QuantumDecapsulateSecretSpec {
	if in == nil {
		return nil
	}
	out := new(QuantumDecapsulateSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumDecapsulateSecretStatus) DeepCopyInto(out *QuantumDecapsulateSecretStatus) {
	*out = *in
	if in.SharedSecretReference != nil {
		in, out := &in.SharedSecretReference, &out.SharedSecretReference
		*out = new(ObjectReference)
		**out = **in
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumDecapsulateSecretStatus.
func (in *QuantumDecapsulateSecretStatus) DeepCopy() *QuantumDecapsulateSecretStatus {
	if in == nil {
		return nil
	}
	out := new(QuantumDecapsulateSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumDerivedKey) DeepCopyInto(out *QuantumDerivedKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumDerivedKey.
func (in *QuantumDerivedKey) DeepCopy() *QuantumDerivedKey {
	if in == nil {
		return nil
	}
	out := new(QuantumDerivedKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumDerivedKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumDerivedKeyList) DeepCopyInto(out *QuantumDerivedKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QuantumDerivedKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumDerivedKeyList.
func (in *QuantumDerivedKeyList) DeepCopy() *QuantumDerivedKeyList {
	if in == nil {
		return nil
	}
	out := new(QuantumDerivedKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumDerivedKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumDerivedKeySpec) DeepCopyInto(out *QuantumDerivedKeySpec) {
	*out = *in
	out.SharedSecretRef = in.SharedSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumDerivedKeySpec.
func (in *QuantumDerivedKeySpec) DeepCopy() *QuantumDerivedKeySpec {
	if in == nil {
		return nil
	}
	out := new(QuantumDerivedKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumDerivedKeyStatus) DeepCopyInto(out *QuantumDerivedKeyStatus) {
	*out = *in
	if in.DerivedKeyReference != nil {
		in, out := &in.DerivedKeyReference, &out.DerivedKeyReference
		*out = new(ObjectReference)
		**out = **in
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumDerivedKeyStatus.
func (in *QuantumDerivedKeyStatus) DeepCopy() *QuantumDerivedKeyStatus {
	if in == nil {
		return nil
	}
	out := new(QuantumDerivedKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumEncapsulateSecret) DeepCopyInto(out *QuantumEncapsulateSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumEncapsulateSecret.
func (in *QuantumEncapsulateSecret) DeepCopy() *QuantumEncapsulateSecret {
	if in == nil {
		return nil
	}
	out := new(QuantumEncapsulateSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumEncapsulateSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumEncapsulateSecretList) DeepCopyInto(out *QuantumEncapsulateSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QuantumEncapsulateSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumEncapsulateSecretList.
func (in *QuantumEncapsulateSecretList) DeepCopy() *QuantumEncapsulateSecretList {
	if in == nil {
		return nil
	}
	out := new(QuantumEncapsulateSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumEncapsulateSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumEncapsulateSecretSpec) DeepCopyInto(out *QuantumEncapsulateSecretSpec) {
	*out = *in
	out.PublicKeyRef = in.PublicKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumEncapsulateSecretSpec.
func (in *QuantumEncapsulateSecretSpec) DeepCopy() *QuantumEncapsulateSecretSpec {
	if in == nil {
		return nil
	}
	out := new(QuantumEncapsulateSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumEncapsulateSecretStatus) DeepCopyInto(out *QuantumEncapsulateSecretStatus) {
	*out = *in
	if in.SharedSecretReference != nil {
		in, out := &in.SharedSecretReference, &out.SharedSecretReference
		*out = new(ObjectReference)
		**out = **in
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumEncapsulateSecretStatus.
func (in *QuantumEncapsulateSecretStatus) DeepCopy() *QuantumEncapsulateSecretStatus {
	if in == nil {
		return nil
	}
	out := new(QuantumEncapsulateSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumKEMKeyPair) DeepCopyInto(out *QuantumKEMKeyPair) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumKEMKeyPair.
func (in *QuantumKEMKeyPair) DeepCopy() *QuantumKEMKeyPair {
	if in == nil {
		return nil
	}
	out := new(QuantumKEMKeyPair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumKEMKeyPair) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumKEMKeyPairList) DeepCopyInto(out *QuantumKEMKeyPairList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QuantumKEMKeyPair, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumKEMKeyPairList.
func (in *QuantumKEMKeyPairList) DeepCopy() *QuantumKEMKeyPairList {
	if in == nil {
		return nil
	}
	out := new(QuantumKEMKeyPairList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumKEMKeyPairList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumKEMKeyPairSpec) DeepCopyInto(out *QuantumKEMKeyPairSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumKEMKeyPairSpec.
func (in *QuantumKEMKeyPairSpec) DeepCopy() *QuantumKEMKeyPairSpec {
	if in == nil {
		return nil
	}
	out := new(QuantumKEMKeyPairSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumKEMKeyPairStatus) DeepCopyInto(out *QuantumKEMKeyPairStatus) {
	*out = *in
	if in.KeyPairReference != nil {
		in, out := &in.KeyPairReference, &out.KeyPairReference
		*out = new(ObjectReference)
		**out = **in
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumKEMKeyPairStatus.
func (in *QuantumKEMKeyPairStatus) DeepCopy() *QuantumKEMKeyPairStatus {
	if in == nil {
		return nil
	}
	out := new(QuantumKEMKeyPairStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumRandomNumber) DeepCopyInto(out *QuantumRandomNumber) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumRandomNumber.
func (in *QuantumRandomNumber) DeepCopy() *QuantumRandomNumber {
	if in == nil {
		return nil
	}
	out := new(QuantumRandomNumber)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumRandomNumber) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumRandomNumberList) DeepCopyInto(out *QuantumRandomNumberList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QuantumRandomNumber, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumRandomNumberList.
func (in *QuantumRandomNumberList) DeepCopy() *QuantumRandomNumberList {
	if in == nil {
		return nil
	}
	out := new(QuantumRandomNumberList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumRandomNumberList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumRandomNumberSpec) DeepCopyInto(out *QuantumRandomNumberSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumRandomNumberSpec.
func (in *QuantumRandomNumberSpec) DeepCopy() *QuantumRandomNumberSpec {
	if in == nil {
		return nil
	}
	out := new(QuantumRandomNumberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumRandomNumberStatus) DeepCopyInto(out *QuantumRandomNumberStatus) {
	*out = *in
	if in.RandomNumberReference != nil {
		in, out := &in.RandomNumberReference, &out.RandomNumberReference
		*out = new(ObjectReference)
		**out = **in
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumRandomNumberStatus.
func (in *QuantumRandomNumberStatus) DeepCopy() *QuantumRandomNumberStatus {
	if in == nil {
		return nil
	}
	out := new(QuantumRandomNumberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumSignatureKeyPair) DeepCopyInto(out *QuantumSignatureKeyPair) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumSignatureKeyPair.
func (in *QuantumSignatureKeyPair) DeepCopy() *QuantumSignatureKeyPair {
	if in == nil {
		return nil
	}
	out := new(QuantumSignatureKeyPair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumSignatureKeyPair) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumSignatureKeyPairList) DeepCopyInto(out *QuantumSignatureKeyPairList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QuantumSignatureKeyPair, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumSignatureKeyPairList.
func (in *QuantumSignatureKeyPairList) DeepCopy() *QuantumSignatureKeyPairList {
	if in == nil {
		return nil
	}
	out := new(QuantumSignatureKeyPairList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumSignatureKeyPairList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumSignatureKeyPairSpec) DeepCopyInto(out *QuantumSignatureKeyPairSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumSignatureKeyPairSpec.
func (in *QuantumSignatureKeyPairSpec) DeepCopy() *QuantumSignatureKeyPairSpec {
	if in == nil {
		return nil
	}
	out := new(QuantumSignatureKeyPairSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumSignatureKeyPairStatus) DeepCopyInto(out *QuantumSignatureKeyPairStatus) {
	*out = *in
	if in.KeyPairReference != nil {
		in, out := &in.KeyPairReference, &out.KeyPairReference
		*out = new(ObjectReference)
		**out = **in
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumSignatureKeyPairStatus.
func (in *QuantumSignatureKeyPairStatus) DeepCopy() *QuantumSignatureKeyPairStatus {
	if in == nil {
		return nil
	}
	out := new(QuantumSignatureKeyPairStatus)
	in.DeepCopyInto(out)
	return out
}
