---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-qubesec-io-v1-quantumrandomnumber
  failurePolicy: Fail
  name: mquantumrandomnumber.kb.io
  rules:
  - apiGroups:
    - qubesec.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - quantumrandomnumbers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-qubesec-io-v1-quantumrandomnumber
  failurePolicy: Fail
  name: vquantumrandomnumber.kb.io
  rules:
  - apiGroups:
    - qubesec.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - quantumrandomnumbers
  sideEffects: None
