# permissions for end users to edit quantumkemkeypairs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: quantumkemkeypair-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: qubesec
    app.kubernetes.io/part-of: qubesec
    app.kubernetes.io/managed-by: kustomize
  name: quantumkemkeypair-editor-role
rules:
- apiGroups:
  - qubesec.io
  resources:
  - quantumkemkeypairs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qubesec.io
  resources:
  - quantumkemkeypairs/status
  verbs:
  - get
